In [1]:
!pip install pandas
import pandas as pd
df = pd.read_csv(r"C:\Users\HP\Desktop\Machine learning\ai-engineer-roadmap-2026\NLP\Log classification\Training\Dataset\synthetic_logs.csv")
df

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert
...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert

In [2]:
df.source.unique()

<StringArray>
[      'ModernCRM', 'AnalyticsEngine',        'ModernHR',   'BillingSystem',
   'ThirdPartyAPI',       'LegacyCRM']
Length: 6, dtype: str

In [3]:
df.target_label.unique()

<StringArray>
[        'HTTP Status',      'Critical Error',      'Security Alert',
               'Error', 'System Notification',      'Resource Usage',
         'User Action',      'Workflow Error', 'Deprecation Warning']
Length: 9, dtype: str

In [4]:
df[df.target_label=='System Notification'].sample(10)

,timestamp,source,log_message,target_label,complexity
52,11/12/2025 13:13,BillingSystem,Backup completed successfully.,System Notification,regex
1524,11/30/2025 2:39,ThirdPartyAPI,System reboot initiated by user User278.,System Notification,regex
2357,2/21/2025 9:44,ModernHR,System updated to version 1.0.7.,System Notification,regex
1770,10/7/2025 23:19,AnalyticsEngine,Disk cleanup completed successfully.,System Notification,regex
1270,3/20/2025 11:16,BillingSystem,System updated to version 1.5.8.,System Notification,regex
2246,3/2/2025 22:56,ModernHR,System reboot initiated by user User488.,System Notification,regex
1355,5/28/2025 15:26,BillingSystem,Backup completed successfully.,System Notification,regex
1501,3/4/2025 22:32,AnalyticsEngine,Backup completed successfully.,System Notification,regex
1856,6/27/2025 4:56,ModernHR,File data_1714.csv uploaded successfully by us...,System Notification,regex
878,11/10/2025 2:58,AnalyticsEngine,Backup ended at 2025-12-04 02:19:48.,System Notification,regex

In [5]:
df[df.log_message.str.startswith("System reboot initiated by user")]

,timestamp,source,log_message,target_label,complexity
36,11/19/2025 13:14,BillingSystem,System reboot initiated by user User243.,System Notification,regex
92,12/4/2025 21:20,BillingSystem,System reboot initiated by user User471.,System Notification,regex
139,5/8/2025 16:34,ModernHR,System reboot initiated by user User216.,System Notification,regex
140,9/11/2025 8:49,AnalyticsEngine,System reboot initiated by user User639.,System Notification,regex
161,3/31/2025 19:40,BillingSystem,System reboot initiated by user User819.,System Notification,regex
163,6/6/2025 15:29,BillingSystem,System reboot initiated by user User938.,System Notification,regex
307,4/12/2025 0:41,BillingSystem,System reboot initiated by user User929.,System Notification,regex
365,10/20/2025 22:32,ModernHR,System reboot initiated by user User533.,System Notification,regex
508,4/15/2025 2:04,ThirdPartyAPI,System reboot initiated by user User591.,System Notification,regex
552,9/22/2025 20:54,ModernHR,System reboot initiated by user User421.,System Notification,regex
668,9/5/2025 7:14,ModernHR,System reboot initiated by user User297.,System Notification,regex
693,7/6/2025 21:40,BillingSystem,System reboot initiated by user User159.,System Notification,regex
697,3/13/2025 7:09,BillingSystem,System reboot initiated by user User648.,System Notification,regex
714,9/25/2025 23:35,ThirdPartyAPI,System reboot initiated by user User600.,System Notification,regex
730,5/24/2025 11:08,AnalyticsEngine,System reboot initiated by user User120.,System Notification,regex
800,8/15/2025 12:14,BillingSystem,System reboot initiated by user User901.,System Notification,regex
837,4/9/2025 8:28,AnalyticsEngine,System reboot initiated by user User876.,System Notification,regex
852,3/31/2025 5:20,ModernCRM,System reboot initiated by user User811.,System Notification,regex
865,2/25/2025 1:40,AnalyticsEngine,System reboot initiated by user User964.,System Notification,regex
889,11/30/2025 13:45,ModernHR,System reboot initiated by user User766.,System Notification,regex
896,7/28/2025 11:24,BillingSystem,System reboot initiated by user User765.,System Notification,regex
988,9/11/2025 22:23,BillingSystem,System reboot initiated by user User427.,System Notification,regex
1106,12/28/2025 13:32,ModernHR,System reboot initiated by user User246.,System Notification,regex
1159,8/5/2025 6:52,BillingSystem,System reboot initiated by user User329.,System Notification,regex
1194,7/20/2025 9:10,AnalyticsEngine,System reboot initiated by user User747.,System Notification,regex
1275,7/15/2025 23:37,BillingSystem,System reboot initiated by user User829.,System Notification,regex
1299,7/15/2025 19:19,BillingSystem,System reboot initiated by user User966.,System Notification,regex
1304,8/10/2025 6:18,ThirdPartyAPI,System reboot initiated by user User758.,System Notification,regex
1524,11/30/2025 2:39,ThirdPartyAPI,System reboot initiated by user User278.,System Notification,regex
1562,8/18/2025 4:17,ThirdPartyAPI,System reboot initiated by user User648.,System Notification,regex
1624,12/14/2025 5:14,AnalyticsEngine,System reboot initiated by user User268.,System Notification,regex
1663,10/27/2025 22:04,AnalyticsEngine,System reboot initiated by user User315.,System Notification,regex
1776,2/21/2025 11:56,ModernHR,System reboot initiated by user User155.,System Notification,regex
1803,8/22/2025 6:30,AnalyticsEngine,System reboot initiated by user User204.,System Notification,regex
1804,8/26/2025 21:06,ModernHR,System reboot initiated by user User899.,System Notification,regex
1852,1/26/2025 12:34,AnalyticsEngine,System reboot initiated by user User223.,System Notification,regex
1865,5/11/2025 10:58,AnalyticsEngine,System reboot initiated by user User932.,System Notification,regex
1956,9/26/2025 19:32,ThirdPartyAPI,System reboot initiated by user User264.,System Notification,regex
2003,6/23/2025 17:54,ModernCRM,System reboot initiated by user User517.,System Notification,regex
2014,12/25/2025 4:33,AnalyticsEngine,System reboot initiated by user User293.,System Notification,regex
2043,9/12/2025 20:20,ThirdPartyAPI,System reboot initiated by user User262.,System Notification,regex
2074,9/13/2025 8:43,ModernCRM,System reboot initiated by user User937.,System Notification,regex
2228,9/3/2025 11:24,ModernHR,System reboot initiated by user User179.,System Notification,regex
2243,1/16/2025 7:22,ModernHR,System reboot initiated by user User770.,System Notification,regex
2246,3/2/2025 22:56,ModernHR,System reboot initiated by user User488.,System Notification,regex
2253,10/7/2025 2:20,ModernHR,System reboot initiated by user User644.,System Notification,regex
2317,3/7/2025 5:44,BillingSystem,System reboot initiated by user User724.,System Notification,regex
2360,5/1/2025 4:21,ThirdPartyAPI,System reboot initiated by user User876.,System Notification,regex

In [6]:
!pip install sentence-transformers

Collecting sentence-transformers
  Using cached sentence_transformers-5.6.0-py3-none-any.whl.metadata (18 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Using cached transformers-5.12.1-py3-none-any.whl.metadata (33 kB)
Collecting huggingface-hub>=0.23.0 (from sentence-transformers)
  Using cached huggingface_hub-1.20.1-py3-none-any.whl.metadata (14 kB)
Collecting torch>=1.11.0 (from sentence-transformers)
  Using cached torch-2.12.1-cp311-cp311-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: numpy>=1.20.0 in .\.venv\Lib\site-packages (from sentence-transformers) (2.4.6)
Requirement already satisfied: scikit-learn>=0.22.0 in .\.venv\Lib\site-packages (from sentence-transformers) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in .\.venv\Lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in .\.venv\Lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in .\.venv\Lib\site-packages (from sentence-transformers) (4.68.3)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in .\.venv\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in .\.venv\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting typer (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached typer-0.26.7-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: safetensors>=0.4.3 in .\.venv\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: click>=8.4.0 in .\.venv\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in .\.venv\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in .\.venv\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in .\.venv\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Collecting httpx<1,>=0.23.0 (from huggingface-hub>=0.23.0->sentence-transformers)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting typer (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: anyio in .\.venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.0)
Requirement already satisfied: certifi in .\.venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in .\.venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in .\.venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in .\.venv\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in .\.venv\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Collecting rich>=13.8.0 (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: annotated-doc>=0.0.2 in .\.venv\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: colorama in .\.venv\Lib\site-packages (from click>=8.4.0->huggingface-hub>=0.23.0->sentence-transformers) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\.venv\Lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\.venv\Lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in .\.venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Requirement already satisfied: joblib>=1.4.0 in .\.venv\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\.venv\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\.venv\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in .\.venv\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in .\.venv\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in .\.venv\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in .\.venv\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\.venv\Lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in .\.venv\Lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Using cached sentence_transformers-5.6.0-py3-none-any.whl (596 kB)
Using cached transformers-5.12.1-py3-none-any.whl (11.2 MB)
Using cached huggingface_hub-1.20.1-py3-none-any.whl (719 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Using cached typer-0.25.1-py3-none-any.whl (58 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached torch-2.12.1-cp311-cp311-win_amd64.whl (123.0 MB)
Installing collected packages: torch, rich, httpx, typer, huggingface-hub, tokenizers, transformers, sentence-transformers

   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]
   ---------------------------------------- 0/8 [torch]

In [7]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN
import numpy as np

# Load a pre-trained sentence transformer model-light weight embedding model
model = SentenceTransformer('all-MiniLM-L6-v2') 

# Generate embeddings for log messages
embeddings = model.encode(df['log_message'].tolist())


# Apply DBSCAN clustering
clustering = DBSCAN(eps=0.2, min_samples=1,metric='cosine').fit(embeddings)
df['cluster'] = clustering.labels_
df.head()

c:\Users\HP\Desktop\Machine learning\ai-engineer-roadmap-2026\NLP\Log classification\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2667.84it/s]

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [10]:
embeddings[:5].shape

(5, 384)

In [13]:
# Add cluster labels to dataframe
df['cluster'] = clustering.labels_
df.head()

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [15]:
# Group by cluster to inspect patterns
clusters = df.groupby('cluster')['log_message'].apply(list)
sorted_clusters = clusters.sort_values(key=lambda x: x.map(len), ascending=False)

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [19]:
df[df.cluster == 1]

,timestamp,source,log_message,target_label,complexity,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert,1
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,bert,1
248,5/2/2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,bert,1
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,bert,1
361,11/19/2025 23:06,BillingSystem,Email service experienced a sending issue,Error,bert,1
450,10/27/2025 5:59,ThirdPartyAPI,Email delivery system encountered an error,Error,bert,1
477,12/2/2025 10:30,AnalyticsEngine,Email transmission error caused service impact,Critical Error,bert,1
570,11/7/2025 18:08,ThirdPartyAPI,Email service impacted by sending failure,Critical Error,bert,1
678,4/28/2025 15:13,AnalyticsEngine,Email delivery problem affected system,Critical Error,bert,1
695,6/30/2025 12:46,ThirdPartyAPI,Service outage due to email delivery problem,Critical Error,bert,1
816,7/9/2025 9:38,BillingSystem,Error in email delivery affected service,Critical Error,bert,1
926,2/17/2025 8:01,ModernCRM,Email service suffered a delivery failure,Error,bert,1
1011,2/9/2025 17:04,AnalyticsEngine,Error in email sending impacted service,Critical Error,bert,1
1018,2/16/2025 15:02,BillingSystem,Mail service impacted by delivery glitch,Critical Error,bert,1
1046,11/26/2025 22:54,AnalyticsEngine,Email service had a difficulty delivering mess...,Error,bert,1
1058,10/24/2025 5:37,AnalyticsEngine,Email system failed to deliver emails,Error,bert,1
1082,5/17/2025 11:20,ModernHR,Delivery failure impacted email services,Critical Error,bert,1
1151,6/17/2025 15:13,ThirdPartyAPI,Mail service was unable to send emails,Error,bert,1
1176,10/1/2025 12:27,AnalyticsEngine,Email provider faced a delivery challenge,Error,bert,1
1189,2/9/2025 6:15,ModernCRM,Service issue caused by email delivery error,Critical Error,bert,1
1359,8/18/2025 15:58,ModernCRM,Email system down due to sending error,Critical Error,bert,1
1414,6/22/2025 23:07,ModernCRM,Email system encountered a sending error,Error,bert,1
1427,10/26/2025 20:25,ModernHR,Email provider had trouble sending emails,Error,bert,1
1453,9/11/2025 1:18,BillingSystem,Mail delivery error impacted email service,Critical Error,bert,1
1554,3/2/2025 9:21,ModernCRM,Email system had a difficulty sending messages,Error,bert,1
1567,5/11/2025 11:17,ThirdPartyAPI,Email system affected by delivery failure,Critical Error,bert,1
1582,9/10/2025 9:27,BillingSystem,Email delivery failure resulted in service issue,Critical Error,bert,1
1860,6/26/2025 1:08,BillingSystem,Email provider experienced a mail delivery issue,Error,bert,1
1867,10/6/2025 11:04,ModernCRM,Email service had a sending malfunction,Error,bert,1
1901,9/22/2025 2:52,ThirdPartyAPI,Email service experienced a mail sending issue,Error,bert,1
1972,3/12/2025 3:48,ThirdPartyAPI,Delivery issue with email service caused outage,Critical Error,bert,1
2049,10/1/2025 22:07,AnalyticsEngine,Email server experienced a delivery problem,Error,bert,1
2165,4/4/2025 16:11,ThirdPartyAPI,Email server had trouble transmitting emails,Error,bert,1
2281,3/23/2025 20:12,ThirdPartyAPI,Mail delivery issue caused service disruption,Critical Error,bert,1
2284,10/4/2025 18:15,BillingSystem,Email service down due to transmission issue,Critical Error,bert,1
2312,3/9/2025 21:16,ModernHR,Email service faced a delivery obstacle,Error,bert,1
2340,3/26/2025 8:10,ModernCRM,Service outage due to email transmission error,Critical Error,bert,1
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1

In [20]:
# sort clusters by size and print 5 log messages for clusters with > 10 records
cluster_counts = df.groupby('cluster').size().sort_values(ascending=False)

for cluster_id, count in cluster_counts.items():
    if count > 10:
        msgs = df[df.cluster == cluster_id]['log_message'].head(5).tolist()
        print(f"Cluster {cluster_id} (count={count}):")
        for m in msgs:
            print(" -", m)
        print()

Cluster 0 (count=1017):
 - nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
 - nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
 - nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
 - nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
 - nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369

Cluster 5 (count=147):
 - nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
 - nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
 - nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
 - nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
 - nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited

Cluster 11 (count=100):
 - User User685 logged out.
 - User User395 logged in.
 - User User225 logged in.
 - User User494 logged out.
 - User User900 logged in.

Cluster 13 (count=86):
 - Backup started at 2025-05-14 07:06:55.
 - Backup started at 2025-02-15 20:00:19.
 - Backup ended at 2025-08-08 13:06:23.
 - Backup started at 2025-11-14 08:27:43.
 - Backup started at 2025-12-09 10:19:11.

Cluster 7 (count=60):
 - Multiple bad login attempts detected on user 8538 account
 - Multiple login failures occurred on user 9052 account
 - User 7153 made multiple incorrect login attempts
 - User 8300 made multiple incorrect login attempts
 - Multiple login failures were detected for user 6373

Cluster 8 (count=60):
 - Backup completed successfully.
 - Backup completed successfully.
 - Backup completed successfully.
 - Backup completed successfully.
 - Backup completed successfully.

Cluster 21 (count=58):
 - System updated to version 3.9.1.
 - System updated to version 5.5.4.
 - System updated to version 4.7.4.
 - System updated to version 3.7.7.
 - System updated to version 2.6.2.

Cluster 3 (count=57):
 - Shard 6 replication task ended in failure
 - Data replication task for shard 14 did not complete
 - Data replication task failed for shard 17
 - Replication of data to shard 14 failed
 - Data replication task for shard 6 did not complete

Cluster 4 (count=53):
 - File data_6169.csv uploaded successfully by user User953.
 - File data_3847.csv uploaded successfully by user User175.
 - File data_7366.csv uploaded successfully by user User282.
 - File data_1206.csv uploaded successfully by user User359.
 - File data_1503.csv uploaded successfully by user User151.

Cluster 17 (count=52):
 - Denied access attempt on restricted account Account2682
 - Unauthorized login attempt on protected account Account5030
 - Account Account9437 blocked due to failed login
 - Account Account7999 access denied due to login failure
 - Invalid login attempt made on secured account Account7864

Cluster 6 (count=51):
 - Critical system unit error: unit ID Component55
 - System component malfunction: component ID Component79
 - Critical system element is down: element ID Component96
 - Essential system part malfunction: part ID Component6
 - Failure occurred in critical system component: component ID Component92

Cluster 32 (count=51):
 - Disk cleanup completed successfully.
 - Disk cleanup completed successfully.
 - Disk cleanup completed successfully.
 - Disk cleanup completed successfully.
 - Disk cleanup completed successfully.

Cluster 16 (count=48):
 - System reboot initiated by user User243.
 - System reboot initiated by user User471.
 - System reboot initiated by user User216.
 - System reboot initiated by user User639.
 - System reboot initiated by user User819.

Cluster 20 (count=48):
 - User 7662 tried to bypass API security measures
 - User 2367 failed to provide valid API access credentials
 - User 3569 made an unauthorized API request
 - Unauthorized user 2968 tried to access restricted API
 - User 2186 attempted to access API without proper authorization

Cluster 9 (count=44):
 - Account with ID 5351 created by User634.
 - Account with ID 7813 created by User373.
 - Account with ID 9827 created by User965.
 - Account with ID 2520 created by User546.
 - Account with ID 2300 created by User964.

Cluster 1 (count=39):
 - Email service experiencing issues with sending
 - Email server encountered a sending fault
 - Mail service encountered a delivery glitch
 - Service disruption caused by email sending error
 - Email system had a problem sending emails

Cluster 10 (count=30):
 - nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
 - nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
 - nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
 - nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
 - nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]

Cluster 34 (count=25):
 - Abnormal behavior found on server 10, possible security threat
 - Security alert: suspicious activity on server 1
 - Anomalous activity identified on server 23, security review recommended
 - Server 27 experienced potential security incident, review required
 - Server 36 experienced potential security incident, review required

Cluster 53 (count=20):
 - Module X experienced an invalid data format issue
 - Input format mismatch occurred in module X
 - Module X reported an error in input format validation
 - Module X failed to process input due to formatting error
 - Input data format in module X was invalid or corrupted

Cluster 14 (count=20):
 - Detection of multiple disk faults in RAID setup
 - RAID array suffered multiple hard drive failures
 - RAID array experienced multiple disk crashes
 - Multiple hard drive issues in RAID configuration found
 - Identification of multiple faulty disks in RAID array

Cluster 52 (count=20):
 - Service health check was not successful because of SSL certificate validation failures.
 - Invalid SSL certificate resulted in a failed service health check.
 - Service health check failure was due to an invalid or improperly configured SSL certificate.
 - An issue with the SSL certificate caused the service health check to fail.
 - Service health check failure was caused by an expired SSL certificate.

Cluster 18 (count=17):
 - Boot process terminated unexpectedly due to kernel issue
 - System encountered kernel panic during initialization phase
 - Boot process was stopped by kernel malfunction
 - System encountered kernel failure during bootup sequence
 - Boot sequence failed due to kernel panic

Cluster 42 (count=13):
 - User 5127 has escalated admin privileges without authorization
 - User 9745 has escalated to admin level
 - User 8483 escalated privileges to admin level
 - User 1987 has escalated to admin level
 - User 8395 escalated privileges to admin level

Cluster 25 (count=13):
 - System configuration is no longer valid
 - Configuration is corrupted throughout the system
 - Cross-system configuration failure occurred
 - System configuration is experiencing errors
 - Configuration malfunction is system-wide

Cluster 59 (count=12):
 - Potential security threat: Admin privilege escalation for user 5130
 - Admin privilege escalation alert for user 2893
 - Admin privilege escalation alert for user 8532
 - Potential security threat: Admin privilege escalation for user 1554
 - Warning: Potential admin privilege escalation for user 5720

Cluster 26 (count=11):
 - Privilege elevation detected for user 5038
 - Elevation of admin privileges detected for user 6137
 - Elevation of admin privileges detected for user 4907
 - User 6069 has been granted elevated admin privileges
 - Admin privilege elevation warning for user 7574

Classification Stage 1: Regex

In [53]:
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message, re.IGNORECASE):
            return label
    return None

# Apply regex classification

In [69]:
classify_with_regex("User User123 logged OUT.")

'User Action'

In [70]:
classify_with_regex("System reboot initiated by user User179.")

'System Notification'

In [71]:
classify_with_regex("Hey you, chill bro")

In [72]:
classify_with_regex("Account with ID 7627 created by surabiga.")

'User Action'

In [73]:
df['regex_label']= df['log_message'].apply(classify_with_regex)
df.head(10)

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,NaN
5,2025-10-09 10:30:31,ModernHR,nova.osapi_compute.wsgi.server [req-f0bffbc3-5...,HTTP Status,bert,0,NaN
6,3/1/2025 19:14,ModernHR,Shard 6 replication task ended in failure,Error,bert,3,NaN
7,10/11/2025 8:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,regex,4,System Notification
8,2025-02-12 10:42:29,ThirdPartyAPI,nova.compute.claims [req-a07ac654-8e81-416d-bf...,Resource Usage,bert,5,NaN
9,2025-03-30 04:01:45,ModernHR,nova.osapi_compute.wsgi.server [req-2bf7cfee-a...,HTTP Status,bert,0,NaN

In [74]:
df[df['regex_label'].isna()].head(25)

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,NaN
5,2025-10-09 10:30:31,ModernHR,nova.osapi_compute.wsgi.server [req-f0bffbc3-5...,HTTP Status,bert,0,NaN
6,3/1/2025 19:14,ModernHR,Shard 6 replication task ended in failure,Error,bert,3,NaN
8,2025-02-12 10:42:29,ThirdPartyAPI,nova.compute.claims [req-a07ac654-8e81-416d-bf...,Resource Usage,bert,5,NaN
9,2025-03-30 04:01:45,ModernHR,nova.osapi_compute.wsgi.server [req-2bf7cfee-a...,HTTP Status,bert,0,NaN
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert,1,NaN
11,6/15/2025 11:44,ModernHR,Critical system unit error: unit ID Component55,Critical Error,bert,6,NaN
12,2025-07-12 03:03:18,ModernHR,nova.osapi_compute.wsgi.server [req-d4f8d0c2-4...,HTTP Status,bert,0,NaN
13,8/4/2025 19:57,ThirdPartyAPI,Multiple bad login attempts detected on user 8...,Security Alert,bert,7,NaN
16,2025-11-15 14:48:30,BillingSystem,nova.osapi_compute.wsgi.server [req-6fe0e366-f...,HTTP Status,bert,0,NaN
17,2025-01-27 12:39:05,ModernCRM,nova.osapi_compute.wsgi.server [req-5f1c2027-e...,HTTP Status,bert,0,NaN
19,2025-07-10 01:17:59,BillingSystem,nova.osapi_compute.wsgi.server [req-945d1f31-a...,HTTP Status,bert,0,NaN
20,2025-12-27 12:52:25,ThirdPartyAPI,nova.osapi_compute.wsgi.server [req-033d97b9-6...,HTTP Status,bert,0,NaN
21,2025-03-01 19:16:10,ModernCRM,nova.osapi_compute.wsgi.server [req-75bc6269-8...,HTTP Status,bert,0,NaN
22,2025-08-28 03:54:33,ThirdPartyAPI,nova.compute.resource_tracker [req-addc1839-2e...,Resource Usage,bert,10,NaN
23,2025-09-01 18:46:38,ModernHR,nova.osapi_compute.wsgi.server [req-077c3c87-b...,HTTP Status,bert,0,NaN
24,2025-12-16 23:18:28,ModernCRM,nova.osapi_compute.wsgi.server [req-4e83daf7-a...,HTTP Status,bert,0,NaN
25,2025-02-15 09:00:40,AnalyticsEngine,nova.osapi_compute.wsgi.server [req-bfce366e-9...,HTTP Status,bert,0,NaN
26,2025-03-03 17:11:11,ModernCRM,nova.compute.claims [req-d6986b54-3735-4a42-90...,Resource Usage,bert,5,NaN
28,2025-07-31 07:47:02,AnalyticsEngine,nova.osapi_compute.wsgi.server [req-5e6e042b-f...,HTTP Status,bert,0,NaN
29,3/10/2025 23:11,AnalyticsEngine,Alert: brute force login attempt from 192.168....,Security Alert,bert,12,NaN

In [75]:
df[df['regex_label'].notnull()].shape

(500, 7)

In [76]:
df.shape

(2410, 7)

Classification Stage 2: Classification Using Embeddings-BERT

In [77]:
df_non_regex = df[df['regex_label'].isna()].copy()
df_non_regex.head(10)
df_non_regex.shape

(1910, 7)

In [78]:
df_legacy = df_non_regex[df_non_regex.source=="LegacyCRM"]
df_legacy

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
60,2025-10-06 16:55:23,LegacyCRM,Lead conversion failed for prospect ID 7842 du...,Workflow Error,llm,24,NaN
255,2025-05-03 16:55:35,LegacyCRM,API endpoint 'getCustomerDetails' is deprecate...,Deprecation Warning,llm,48,NaN
377,2025-06-24 12:16:29,LegacyCRM,Customer follow-up process for lead ID 5621 fa...,Workflow Error,llm,62,NaN
1325,2025-04-17 07:33:44,LegacyCRM,Escalation rule execution failed for ticket ID...,Workflow Error,llm,105,NaN
1734,2025-04-30 07:47:30,LegacyCRM,The 'ExportToCSV' feature is outdated. Please ...,Deprecation Warning,llm,118,NaN
1826,2025-01-23 10:33:36,LegacyCRM,Support for legacy authentication methods will...,Deprecation Warning,llm,122,NaN
2217,2025-05-12 09:46:54,LegacyCRM,Task assignment for TeamID 3425 could not comp...,Workflow Error,llm,133,NaN

In [79]:
df_non_legacy = df_non_regex[df_non_regex.source!="LegacyCRM"]
df_non_legacy

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,NaN
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0,NaN
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,7,NaN
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0,NaN
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,NaN
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,7,NaN

In [80]:
df_non_legacy.shape

(1903, 7)

In [81]:
model = SentenceTransformer('all-MiniLM-L6-v2')  # Lightweight embedding model
embeddings_filtered = model.encode(df_non_legacy['log_message'].tolist())

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2556.93it/s]

In [82]:
len(embeddings_filtered)

1903

In [83]:
X = embeddings_filtered
y = df_non_legacy['target_label'].values

In [87]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [104]:
import joblib
joblib.dump(clf,'models/log_classifier.joblib')

FileNotFoundError: [Errno 2] No such file or directory: 'models/log_classifier.joblib'

In [106]:
import os
import joblib

model_dir = r"C:\Users\HP\Desktop\Machine learning\ai-engineer-roadmap-2026\NLP\Log classification\Training\models"
os.makedirs(model_dir, exist_ok=True)

model_path = os.path.join(model_dir, "log_classifier.joblib")

joblib.dump(clf, model_path)

print("Model saved at:", model_path)

Model saved at: C:\Users\HP\Desktop\Machine learning\ai-engineer-roadmap-2026\NLP\Log classification\Training\models\log_classifier.joblib